title:      Robert Smith
logo: "https://raw.githubusercontent.com/SimpleStepper/Portfolio/main/assets/img/me2.png"
Description: This is my online portfolio to showcase data analytics projects. Let's connect on [LinkedIn.](https://www.linkedin.com/in/rs4l/)
#show_downloads: false
#show_github_link: false
theme: jekyll-theme-minimal
